const DashData = [
  {
    id: 1,
    name: "Shakirat Akanji",
    date: "1/5/2023",
    analyst: "Tofunmi",
    status: "Approved",
  },
  {
    id: 2,
    name: "Tofunmi Idowu",
    date: "30/4/2023",
    analyst: "Constance",
    status: "Pending",
  },
  {
    id: 3,
    name: "Naomi Igimoh",
    date: "25/4/2023",
    analyst: "Shakirat",
    status: "Disapproved",
  },

  {
    id: 4,
    name: "Edu Hermans",
    date: "20/4/2023",
    analyst: "Tofunmi",
    status: "Approved",
  },
  {
    id: 5,
    name: "Edu Hermans",
    date: "20/4/2023",
    analyst: "Tofunmi",
    status: "Approved",
  },
  {
    id: 6,
    name: "Edu Hermans",
    date: "20/4/2023",
    analyst: "Tofunmi",
    status: "Approved",
  },
  {
    id: 7,
    name: "Edu Hermans",
    date: "20/4/2023",
    analyst: "Tofunmi",
    status: "Approved",
  },
  {
    id: 8,
    name: "Edu Hermans",
    date: "20/4/2023",
    analyst: "Tofunmi",
    status: "Approved",
  },
  {
    id: 9,
    name: "Edu Hermans",
    date: "20/4/2023",
    analyst: "Tofunmi",
    status: "Approved",
  },
  {
    id: 10,
    name: "Edu Hermans",
    date: "20/4/2023",
    analyst: "Tofunmi",
    status: "Approved",
  },
  {
    id: 11,
    name: "Edu Hermans",
    date: "20/4/2023",
    analyst: "Tofunmi",
    status: "Approved",
  },
  {
    id: 12,
    name: "Edu Hermans",
    date: "20/4/2023",
    analyst: "Tofunmi",
    status: "Approved",
  },
];
export default DashData;
