

const ApplicationData = [
    {
        id: 1,
        name: 'Shakirat Akanji',
        date: '1/5/2023',
        analyst: 'Tofunmi',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 2,
        name: 'Tofunmi Idowu',
        date: '30/4/2023',
        analyst: 'Constance',
        status: 'Pending',
        action: 'Download',
    },
    {
        id: 3,
        name: 'Naomi Igimoh',
        date: '25/4/2023',
        analyst: 'Shakirat',
        status: 'Disapproved',
        action: 'Download',
    },
    {
        id: 4,
        name: 'Edu Hermans',
        date: '20/4/2023',
        analyst: 'Tofunmi',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 5,
        name: 'Timmy Adubi',
        date: '20/4/2023',
        analyst: 'Tofunmi',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 6,
        name: 'Alex Oyebade',
        date: '20/4/2023',
        analyst: 'Shakirat',
        status: 'Disapproved',
        action: 'Download',
    },
    {
        id: 7,
        name: 'Ekene Smart',
        date: '20/4/2023',
        analyst: 'Shakirat',
        status: 'Disapproved',
        action: 'Download',
    },
    {
        id: 8,
        name: 'Adesewa fig',
        date: '20/4/2023',
        analyst: 'Constance',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 9,
        name: 'Jane Ibude',
        date: '20/4/2023',
        analyst: 'Shakirat',
        status: 'Pending',
        action: 'Download',
    },
    {
        id: 10,
        name: 'Habiba Anu',
        date: '20/4/2023',
        analyst: 'Tofunmi',
        status: 'Pending',
        action: 'Download',
    },
    {
        id: 11,
        name: 'Ridwan Bolaji',
        date: '20/4/2023',
        analyst: 'Tofunmi',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 12,
        name: 'Aishat Amoke',
        date: '20/4/2023',
        analyst: 'Constance',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 13,
        name: 'Aishat Amoke',
        date: '20/4/2023',
        analyst: 'Constance',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 14,
        name: 'Aishat Amoke',
        date: '20/4/2023',
        analyst: 'Constance',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 15,
        name: 'Aishat Amoke',
        date: '20/4/2023',
        analyst: 'Constance',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 16,
        name: 'Aishat Amoke',
        date: '20/4/2023',
        analyst: 'Constance',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 17,
        name: 'Aishat Amoke',
        date: '20/4/2023',
        analyst: 'Constance',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 18,
        name: 'Shakirat Akanji',
        date: '1/5/2023',
        analyst: 'Tofunmi',
        status: 'Approved',
        action: 'Download',
    }, {
        id: 19,
        name: 'Shakirat Akanji',
        date: '1/5/2023',
        analyst: 'Tofunmi',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 20,
        name: 'Tofunmi Idowu',
        date: '30/4/2023',
        analyst: 'Constance',
        status: 'Pending',
        action: 'Download',
    },
    {
        id: 21,
        name: 'Tofunmi Idowu',
        date: '30/4/2023',
        analyst: 'Constance',
        status: 'Pending',
        action: 'Download',
    },
    {
        id: 22,
        name: 'Tofunmi Idowu',
        date: '30/4/2023',
        analyst: 'Constance',
        status: 'Pending',
        action: 'Download',
    },
    {
        id: 23,
        name: 'Naomi Igimoh',
        date: '25/4/2023',
        analyst: 'Shakirat',
        status: 'Disapproved',
        action: 'Download',
    },
    {
        id: 24,
        name: 'Naomi Igimoh',
        date: '25/4/2023',
        analyst: 'Shakirat',
        status: 'Disapproved',
        action: 'Download',
    },
    {
        id: 25,
        name: 'Naomi Igimoh',
        date: '25/4/2023',
        analyst: 'Shakirat',
        status: 'Disapproved',
        action: 'Download',
    },
    {
        id: 26,
        name: 'Naomi Igimoh',
        date: '25/4/2023',
        analyst: 'Shakirat',
        status: 'Disapproved',
        action: 'Download',
    },
    {
        id: 27,
        name: 'Naomi Igimoh',
        date: '25/4/2023',
        analyst: 'Shakirat',
        status: 'Disapproved',
        action: 'Download',
    },
    {
        id: 28,
        name: 'Edu Hermans',
        date: '20/4/2023',
        analyst: 'Tofunmi',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 29,
        name: 'Edu Hermans',
        date: '20/4/2023',
        analyst: 'Tofunmi',
        status: 'Approved',
        action: 'Download',
    },
    {
        id: 30,
        name: 'Edu Hermans',
        date: '20/4/2023',
        analyst: 'Tofunmi',
        status: 'Approved',
        action: 'Download',
    },
];

export default ApplicationData;