/*
 * Copyright (c) 2023 Your Company Name
 * All rights reserved.
 */
const teamsdata = [

    { 
      no: 1, 
      userID: "PRE0001A", 
      name: "Tofunmi Idowun", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 2, 
      userID: "PRE0002U", 
      name: "Constance", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 3, 
      userID: "PRE0003A", 
      name: "Shakira Akanji", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 4, 
      userID: "PRE0004U", 
      name: "Edu Hermans", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 5, 
      userID: "PRE0005U", 
      name: "Abdulqudus Adegbite", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 6, 
      userID: "PRE0006U", 
      name: "Mercy Hanns", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 7, 
      userID: "PRE0007U", 
      name: "Adesewa Smart", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 8, 
      userID: "PRE0008U", 
      name: "Constance", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 9, 
      userID: "PRE0009U", 
      name: "Alex Oyebade", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 10, 
      userID: "PRE0010U", 
      name: "Chiwendu Adams", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 11, 
      userID: "PRE0011U", 
      name: "Timmy Adubi", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 12, 
      userID: "PRE0012U", 
      name: "Tofunmi", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    { 
      no: 13, 
      userID: "PRE0013A", 
      name: "Tofunmi Idowun", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 14, 
      userID: "PRE0014U", 
      name: "Constance", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 15, 
      userID: "PRE0015A", 
      name: "Shakira Akanji", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 16, 
      userID: "PRE0016U", 
      name: "Edu Hermans", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 17, 
      userID: "PRE0017U", 
      name: "Abdulqudus Adegbite", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 18, 
      userID: "PRE0018U", 
      name: "Mercy Hanns", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 19, 
      userID: "PRE0019U", 
      name: "Adesewa Smart", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 20, 
      userID: "PRE0020U", 
      name: "Constance", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 21, 
      userID: "PRE0021U", 
      name: "Alex Oyebade", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 22, 
      userID: "PRE0022U", 
      name: "Chiwendu Adams", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 23, 
      userID: "PRE0023U", 
      name: "Timmy Adubi", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 24, 
      userID: "PRE0024U", 
      name: "Tofunmi", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    { 
      no: 25, 
      userID: "PRE0025A", 
      name: "Tofunmi Idowun", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 26, 
      userID: "PRE0026U", 
      name: "Constance", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 27, 
      userID: "PRE0027A", 
      name: "Shakira Akanji", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 28, 
      userID: "PRE0028U", 
      name: "Edu Hermans", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 29, 
      userID: "PRE0029U", 
      name: "Abdulqudus Adegbite", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 30, 
      userID: "PRE0030U", 
      name: "Mercy Hanns", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 31, 
      userID: "PRE0031U", 
      name: "Adesewa Smart", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 32, 
      userID: "PRE0032U", 
      name: "Constance", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 33, 
      userID: "PRE0033U", 
      name: "Alex Oyebade", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 34, 
      userID: "PRE0034U", 
      name: "Chiwendu Adams", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 35, 
      userID: "PRE0035U", 
      name: "Timmy Adubi", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 36, 
      userID: "PRE0036U", 
      name: "Tofunmi", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    { 
      no: 37, 
      userID: "PRE0037A", 
      name: "Tofunmi Idowun", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 38, 
      userID: "PRE0038U", 
      name: "Constance", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 39, 
      userID: "PRE0039A", 
      name: "Shakira Akanji", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 40, 
      userID: "PRE0040U", 
      name: "Edu Hermans", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 41, 
      userID: "PRE0041U", 
      name: "Abdulqudus Adegbite", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 42, 
      userID: "PRE0042U", 
      name: "Mercy Hanns", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 43, 
      userID: "PRE0043U", 
      name: "Adesewa Smart", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 44, 
      userID: "PRE0044U", 
      name: "Constance", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 45, 
      userID: "PRE0045U", 
      name: "Alex Oyebade", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 46, 
      userID: "PRE0046U", 
      name: "Chiwendu Adams", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 47, 
      userID: "PRE0047U", 
      name: "Timmy Adubi", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 48, 
      userID: "PRE0048U", 
      name: "Tofunmi", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    { 
      no: 49, 
      userID: "PRE0049A", 
      name: "Tofunmi Idowun", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 50, 
      userID: "PRE0050U", 
      name: "Constance", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 51, 
      userID: "PRE0051A", 
      name: "Shakira Akanji", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 52, 
      userID: "PRE0052U", 
      name: "Edu Hermans", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 53, 
      userID: "PRE0053U", 
      name: "Abdulqudus Adegbite", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 54, 
      userID: "PRE0054U", 
      name: "Mercy Hanns", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 55, 
      userID: "PRE0055U", 
      name: "Adesewa Smart", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 56, 
      userID: "PRE0056U", 
      name: "Constance", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 57, 
      userID: "PRE0057U", 
      name: "Alex Oyebade", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 58, 
      userID: "PRE0058U", 
      name: "Chiwendu Adams", 
      role: "Analyst", 
      lastSeen: "30/4/2023", 
    },
    {
      no: 59, 
      userID: "PRE0059U", 
      name: "Timmy Adubi", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
    {
      no: 60, 
      userID: "PRE0060U", 
      name: "Tofunmi", 
      role: "Admin", 
      lastSeen: "1/5/2023", 
    },
  ]
  export default teamsdata;